spring.application.name=MotorReservasHotel
spring.datasource.url=jdbc:postgresql://localhost:5432/motor_reservas_hotel
spring.datasource.username=postgres
spring.datasource.password=

# ADD OR MODIFY WITH JAVA ENTITIES
spring.jpa.hibernate.ddl-auto=update

# SHOW SQL ON CONSOLE
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect