spring.application.name=MotorReservasHotel
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# ADD OR MODIFY WITH JAVA ENTITIES
spring.jpa.hibernate.ddl-auto=update

# SHOW SQL ON CONSOLE
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect